<?php 
	
/*
 *
 * @file
 * Gallery Client Function
 */

function gallery_access_menu(){
  $items['gallery/access_denied'] = array(
    'title' => 'Acceso Denegado',
    'page callback' => 'gallery_access_denied',
    'access callback' => true,
    'type' => MENU_CALLBACK
  );

  $items['download_img'] = array(
    'title' => 'Descargar Imagen',
    'page callback' => 'gallery_access_download',
    'access callback' => true,
    'type' => MENU_CALLBACK
  );
  return $items;
}

function gallery_access_preprocess_node(&$variables){
  global $user;
  $role = array_search('cliente', $user->roles);
  if ($role) {
    if ($variables['node']->type == 'gallery') {
      $current_user = $user->uid;
      $gallery_user = $variables['node']->field_client['und'][0]['target_id'];
      if ($current_user != $gallery_user) {
  	    drupal_goto('gallery/access_denied');
  	  }
    }  
  }
}

function gallery_access_denied(){
  return "<div class='acceso_denegado'>Acceso Denegado</div>";
}

function gallery_access_views_pre_render(&$view){
  $current_path = current_path();
  if ($current_path == "galerias") {
  	global $user;
    $role = array_search('cliente', $user->roles);
    $anonimo = array_search('anonymous user', $user->roles);
    $administrador = array_search('administrator', $user->roles);
    $fotografo = array_search('fotografo', $user->roles);
    $webmaster = array_search('webmaster', $user->roles);
    
    if ($anonimo) {
      drupal_goto('gallery/access_denied');
    }
    if ($administrador) {
      drupal_goto('admin/galerias_admin');
    }
    if ($fotografo) {
      drupal_goto('admin/galerias_fotografos');
    }
    if ($webmaster) {
      drupal_goto('admin/galerias_admin');
    }
  }
  
}

function gallery_access_download(){
  global $user;
  $url = $_GET['url_download'];

  //Se implementa API de evento log para crear nuevo tipo de log de descarga de archivo
  $log = array(
    'type' => 'Descarga',
    'operation' => 'Imagen Galeria',
    'description' => 'Descarga de imagen: ' . $url,
    'uid' => $user->uid,
  );
  event_log_insert($log);
  
  //SE inicia procceso de descarga de la imagen
  $urle = explode('sites', $url);
  header('Content-Type: application/octet-stream');
  header('Content-Disposition: attachment; filename="' . basename('sites'.$urle[1]) . '"');
  header('Content-Length: ' . filesize('sites'.$urle[1]));
  readfile('sites'.$urle[1]);
}

function gallery_access_user_login(&$edit, $account){
  $role = array_search('cliente', $account->roles);
  $administrador = array_search('administrator', $account->roles);
  $fotografo = array_search('fotografo', $account->roles);
  $webmaster = array_search('webmaster', $account->roles);
  if ($role) {
    drupal_goto('galerias/todas');
  }
  if ($administrador) {
    drupal_goto('admin/galerias_admin');
  }
  if ($fotografo) {
    drupal_goto('admin/galerias_fotografos');
  }
  if ($webmaster) {
    drupal_goto('admin/galerias_admin');
  }
}
